# Всі помилки, баги, пропозиції та інше прохання писати на гітхабі
issues: "https://github.com/Leymooo/BungeeCord/issues"
help: "http://www.rubukkit.org/threads/137038/"
bot-filter-version: "3.8.13"

# Не використовуйте '\n', використовуйте %nl%
messages:
  prefix: "&b&lBot&d&lFilter"
  checking: "%prefix%&7>> &aЧекайте на завершення перевірки..."
  checking-captcha: "%prefix%&7>> &aВведіть номер з картинки в чат"
  checking-captcha-wrong: "%prefix%&7>> &cВи ввели капчу неправильно, будь ласка, спробуйте ще раз. У вас &a%s &c%s"
  successfully: "%prefix%&7>> &aПроверка пройдена, приятной игры"
  kick-many-checks: "%prefix%%nl%%nl%&cЗ вашого айпі помічено підозрілу активність%nl%%nl%&6Повторіть спробу через 10 хвилин"
  kick-not-player: "%prefix%%nl%%nl%&cВи не пройшли перевірку, можливо ви бот%nl%&7&oЯкщо це не так, будь ласка, повторіть спробу"
  kick-country: "%prefix%%nl%%nl%&cВаша країна заборонена на сервері"
  kick-big-ping: "%prefix%%nl%%nl%&cУ вас дуже високий пінг, швидше за все ви бот"
  # Title%nl%Subtitle
  # Залишіть порожнім, щоб вимкнути( прм: CHECKING_TITLE = "" )
   # Відключення титлів може трохи покращити продуктивність
  checking-title: "&r&lBot&b&lFilter%nl%&aЙде перевірка"
  checking-title-sus: "&rПроверка пройдена%nl%&aПриємної гри"
  checking-title-captcha: " %nl%&rВведіть капчу в чат"

# Налаштування віртуального світу
dimensions:
   # Який світ використовувати
   # 0 - Звичайний світ
   # 1 - Пекло
   # 2 - Енд
  type: 0

# Увімкнути або вимкнути GeoIp
geo-ip:
  # Коли працює перевірка
   # 0 - Завжди
   # 1 - Тільки під час бот атаки
   # 2 - Вимкнути
  mode: 1
  # Как именно работает GeoIp
  # 0 - White list(Зайти можуть лише ті країни, які є у списку)
  # 1 - Black list(Зайти можуть тільки ті країни, яких немає у списку)
  type: 0
  # Звідки качати GEOIP
   # Змінюйте посилання якщо з якоїсь причини не хитається з цієї
   # Файл повинен закінчуватися на .mmdb або бути запакований у .tar.gz
  new-geoip-download-url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=%license_key%&suffix=tar.gz"
  # ЕЯкщо ключ перестане працювати, то для того щоб отримати новий необхідно зареєструватися на https://www.maxmind.com/
   # та згенерувати новий ключ на сторінці https://www.maxmind.com/en/accounts/current/license-key
  maxmind-license-key: "P5g0fVdAQIq8yQau"
  # Разрешённые странны
  allowed-countries: 
  - "UA"
  - "BY"
  - "EE"
  - "MD"
  - "KG"
  - "AZ"
  - "LT"
  - "LV"
  - "GE"
  - "PL"

# Включити чи вимкнути перевірку на високий пінг
ping-check:
  # Коли працює перевірка
   # 0 - Завжди
   # 1 - Тільки під час бот атаки
   # 2 - Вимкнути
  mode: 1
  # Максимальний допустимий пінг
  max-ping: 350

# Увімкнути або вимкнути перевірку на пряме підключення
server-ping-check:
  # Коли працює перевірка
   # 0 - Завжди
   # 1 - Тільки під час бот атаки
   # 2 - Вимкнути
   # За замовчуванням відключено, оскільки працює не дуже стабільно, під час сильних атак
  mode: 2
  # Протягом якого часу можна заходити на сервер після отримання сервера
  cache-time: 12
  kick-message: 
  - "%nl%"
  - "%nl%"
  - "&cВи були кікнути! Не використовуйте пряме підключення"
  - "%nl%"
  - "%nl%"
  - "&bДля того, щоб зайти на сервер:"
  - "%nl%"
  - "&71) &rДодайте сервер у &lссписок серверів."
  - "%nl%"
  - "&lНаш айпі &8>> de2.mineconnect.xyz:25659 &b&lIP"
  - "%nl%"
  - "%nl%"
  - "&72) &rОновіть список серверів. "
  - "%nl%"
  - "&oЩоб його оновити, натисніть кнопку &c&lОновити &r&oили &c&lRefresh"
  - "%nl%"
  - "%nl%"
  - "&73) &rЗачекайте &c1-3&r секунди та заходьте!"

# Налаштування як саме працюватиме захист
# 0 - Тільки перевірка за допомогою капчі
# 1 - Перевірка на падіння + капча
# 2 - Перевірка на падіння, якщо провалилася, то капча
protection:
  # Режим роботи поки що немає атаки
  normal: 1
  # Режим роботи під час атаки
  on-attack: 1
  # Чи включити постійну перевірку гравців під час заходу?
   # Включаючи цю функцію, не забудьте збільшити ліміти у protection-threshold
  always-check: true
  # Чи перевіряти гравців у яких іп 127.0.0.1?
   # Може бути корисним при використанні Geyser
   # 0 - перевіряти
   # 1 - вимкнути перевірку
   # 2 - перевіряти при кожному заході
  check-localhost: 0
  # Чи вимкнути перевірку для клієнтів із Geyser-standalone? Тип авторищації повинен бути floodgate.
  skip-geyser: false

# Налаштування датабази
sql:
  # Тип датабази. sqlite або mysql
  storage-type: "sqlite"
  # Через скільки днів видаляти гравців із датабази, які пройшли перевірку та більше не заходили. 0 або менше, щоб вимкнути
  purge-time: 14
  # Налаштування для mysql
  hostname: "127.0.0.1"
  port: 3306
  user: "user"
  password: "password"
  database: "database"
  # Інтервал у мілісекундах, як часто синхронізувати базу даних, якщо використовується мультибанжа
  sync-interval: -1
# Скільки гравців/ботів має зайти за 1 хвилину, щоб увімкнувся захист
# Рекомендовані параметри коли немає реклами:
# До 150 онлайн - 25, до 250 - 30, до 350 - 35, до 550 - 40,45, вище - підлаштовувати під себе
# Під час реклами або коли токо, токо поставили захист рекомендується підвищувати ці значення
protection-threshold: 2
# Як довго активний автоматичний захист? У мілісекундах. 1 сек = 1000
protection-time: 120000
# Чи перевіряти на бота при заході на сервер під час бот атаки, чи незалежно проходив перевірку чи ні
force-check-on-attack: true
# Чи показувати онлайн з фільтра
show-online: true
# Скільки часу є у гравця, щоб пройти захист. У мілісекундах. 1 сек = 1000
time-out: 12700
# Чи включити фікс від 'Team 'xxx' already exist in this scoreboard'
fix-scoreboard-teams: true
# Чи записувати IP адреси гравців/ботів, які провалили перевірку у файл?
save-failed-ips-to-file: true
